### ISSUE TITLE
[SUGGESTION] BiomeTweaker support

### ISSUE THREAD

**Issue by Sunconure11** [robertdroptables-mcmods/JEIDsIntegration#6]
If this isn’t already safe with JEID, would it be possible to add an implementation here?

**Comment by sam-kirby** [comment]
Quick look says its fine, if you have problems describe them and reopen this issue.

**Comment by Sunconure11** [comment]
Based on a convo from discord, I recommend reopening this.

https://www.curseforge.com/minecraft/mc-mods/biometweaker

https://www.curseforge.com/minecraft/mc-mods/biometweakercore

**Comment by sam-kirby** [comment]
I've added BiomeTweaker support to JEID, the latest build of which supersedes the need for this mod and is presently available on Github. Hopefully it will be released in the very near future.
